pipeline {
		agent any
		
		stages {
			stage ('clean') {
			steps {
				withMaven(maven : 'maven') {
				sh 'mvn clean'
				}
				}
				}
			stage ('package') {
			steps {
				withMaven(maven : 'maven') {
				sh 'mvn package'	
				}
				}
				}
				}
				}
