pipeline {
		agent any
	
	tools {
		maven 'maven'}
		
		stages {
			stage ('clean') {
			steps {
								
				
				sh 'mvn -f example/pom.xml clean'
				
				}
				}
			stage ('package') {
			steps {
				
				sh 'mvn -f example/pom.xml package'	
				
				}
				}
				}
				}
